name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: NodeJS Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          name: ${{ secrets.EVENT_API_COVERAGE_SECRET }}
          slug: "pauloruan/event-api-test"
