name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Installing Dependencies
        uses: npm install

      - name: Testing Running
        uses: npm run test
